---
title: "GDP per capita"
output: html_document
---

```{r}
library(tidyverse)
library(rnaturalearth)
library(rnaturalearthdata)
library(janitor)
library(gganimate)
library(gifski)
library(transformr)
```

```{r}
gdp_df <- read.csv("gdp.csv", skip = 4) %>% 
  clean_names() %>% 
  select(country_name, country_code, x1994:x2019)


world <- ne_countries(scale = "medium", returnclass = "sf") %>% 
  mutate(country_code = adm0_a3) %>% 
  left_join(. , gdp_df, by="country_code") %>% 
  pivot_longer(cols=starts_with("X"), names_to = "year", values_to = "GDP per capita")
```

```{r}
plot <- ggplot(data = world) +
    geom_sf(aes(fill=`GDP per capita`, group=year)) +
  scale_fill_gradient(trans="log", low="#ffffff", high="#000099") +
  theme(plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        legend.position = "none")
```

```{r}
anim <- plot + transition_states(year, transition_length = 4, state_length = 1) +
  labs(title = 'GDP per capita : {closest_state}',
       caption  = "GDP in Current US$ | Data Source: World Bank Data")
```

```{r}
animate(anim, 200, fps = 20,  width = 1200, height = 1000, 
        renderer = gifski_renderer("gdp.gif"))
```